### ISSUE TITLE
Remove default password from templates

### ISSUE THREAD

**Issue by BorisB2015** [ayesha-kr/covid-one-click-deployment#2]
As a security best practice - please remove default password from here (and other templates like this):

https://github.com/ayesha-kr/covid-one-click-deployment/blob/4b695ce2bf325a6e8e67463f9ca6e8c8b80cb135/datasets/covid-19/definitive-healthcare/customer/templates/azuredeploy.json#L63

**Comment by insidero** [comment]
The reason behind putting the default password is the conditional deployment. We allow the user to choose whether he wants to have a SQL DB or not. If we do not add the default password, the ARM template fails if the user opted for SQL DB and did not provide a password. We obviously would like to change that 'Required' property for password based on the user's decision but that is not possible through the ARM template as we can't update the properties of the parameters dynamically.
